CREATE TABLE [dbo].[acessos](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nome] [varchar](128) NOT NULL,
	[url] [varchar](128) NOT NULL,
	[data] [date] NOT NULL,
 CONSTRAINT [PK_acessos] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
